run_name: "baseline"

improved_tsdf_sampling: True
point_backprojection: True

depth_guidance:
  enabled: True
  pred_depth_dir: /scratch/students/2023-fall-acheche/data/scannet_simplerecon/outputs/converted_depth_est
  depth_scale_augmentation: True
  bp_weighting: "none"
  tsdf_fusion_channel: True
  density_fusion_channel: False

output_sample_rate: 2
reduce_lr_on_plateau: False
no_image_features: False

initial_lr: 0.001
steps: 60_000
finetune_steps: 10_000
n_views_train: 20
n_views_val: 20
workers_train: 8
workers_val: 8
workers_predict: 8
batch_size_per_device: 2
voxel_size: 0.04
crop_size_nvox_train: [96, 96, 56]
crop_size_nvox_val: [96, 96, 96]

dataset_dir: "/scratch/students/2023-fall-acheche/data/scannet/scannet-finerecon/scans"
tsdf_dir: "/scratch/students/2023-fall-acheche/data/scannet/tsdf_gt"

# if no keyframes file is provided then inference will use every frame
test_keyframes_file: "/scratch/students/2023-fall-acheche/ml-finerecon/keyframes.json" #null 

do_prediction_timing: False
